# Ejercicios 

#### I:
1. Crear un tensor de `list(range(9))` e indicar cual es el `size`, `offset`, y `strides`
    * Crear un tensor `b = a.view(3, 3)`. Cual es el valor de `b[1, 1]`
    * crear un tensor `c = b[1:, 1:]`. Cual es el `size`, `offset`, `strides`?
2. Escogan una operacion matematica como cosine o sqrt. Hay una funcion correspondiente en PyTorch?
    * Existe una version de esa operacion que opera `in-place`?

#### II:
1. Crear un tensor 2D y luego agregar una dimension de tamanio 1 insertada en la dimension 0.
2. Eliminar la dimension extra que agrego en el tensor previo.
3. Crear un tensor aleatorio de forma $5x3$ en el intervalo $[3,7)$
4. Crear un tensor con valores de una distribucion normal ($\mu=0, \sigma=1$)
5. Recuperar los indices de todos los elementos no cero en el tensor `torch.Tensor([1,1,1,0,1])`.
6. Crear un tensor aleatorio de forma `(3,1)` y luego apilar cuatro copias horizontalmente.
7. Retornar el producto batch matrix-matrix de dos matrices 3D: (`a=torch.randn(3,4,5)`, `b=torch.rand(3,5,4)`)
8. Retornar el producto batch matrix-matrix de una matriz 3D y una matriz 2D: (`a=torch.rand(3,4,5)`, `b=torch.rand(5,4)`).

In [1]:
import torch

In [5]:
# I. 1)

a=torch.tensor(list(range(9)))
print('Size: ', a.size(), ', Offset:', a.storage_offset(), ', Stride:', a.stride())

b = a.view(3,3)
print('b[1,1]: ', b[1,1])

c = b[1:, 1:]
print('Size: ', c.size(), ', Offset:', c.storage_offset(), ', Stride:', c.stride())

Size:  torch.Size([9]) , Offset: 0 , Stride: (1,)
b[1,1]:  tensor(4)
Size:  torch.Size([2, 2]) , Offset: 4 , Stride: (3, 1)


In [7]:
# I. 2)

adding1 = torch.ones(3)
adding2 = torch.ones(3)
adding1.add_(adding2)
print(adding1)

tensor([2., 2., 2.])


In [8]:
# II. 1)

a = torch.ones([2, 2])
a.unsqueeze_(0)
print(a.size())

torch.Size([1, 2, 2])


In [9]:
# II. 2)

a.resize_((2, 2))
print(a.size())

torch.Size([2, 2])


In [10]:
# II. 3)

a = torch.randint(size = [5, 3], low = 3, high = 7)
print(a)

tensor([[6, 4, 4],
        [4, 3, 3],
        [5, 3, 4],
        [4, 6, 3],
        [3, 4, 5]])


In [11]:
# II. 4)

a = torch.normal(torch.zeros(4), torch.ones(4))
print(a)

tensor([ 0.0019,  0.6937, -0.2154,  0.3806])


In [12]:
# II. 5)

a = torch.Tensor([1, 1, 1, 0, 1])
print((a == 0).nonzero()[0])

tensor([3])


In [13]:
# II. 6) 

a = torch.rand(3, 1)
b = torch.stack([a, a, a, a])
print(b.size())

torch.Size([4, 3, 1])


In [14]:
# II. 7)

a = torch.randn(3, 4, 5) 
b = torch.rand( 3, 5, 4)
product = torch.bmm(a, b)
print(product)

tensor([[[-0.7631, -1.2862, -1.1986, -1.0229],
         [-0.2698, -0.1232, -0.6909, -0.4256],
         [-0.3265, -0.5650, -0.8183, -0.7366],
         [ 1.2105,  2.2873,  2.2266,  2.5940]],

        [[-2.3427, -1.1252, -1.9452, -0.7428],
         [ 0.3229, -0.1487,  0.5748, -0.5402],
         [-3.7081, -3.9644, -5.3413, -3.6767],
         [ 1.4282,  0.2134, -0.8836, -0.5565]],

        [[ 0.7691, -0.8583,  1.1192,  0.2433],
         [-1.6085, -0.5282, -0.0789, -0.4491],
         [ 0.2020,  0.1456, -0.1571,  0.1543],
         [-1.2043,  0.5143, -0.3429, -0.2135]]])


In [15]:
# II. 8)

a = torch.rand(3, 4, 5)
b = torch.rand(5, 4)
product = torch.bmm(a, b.expand(3, 5, 4))
print(product)

tensor([[[1.3894, 1.0237, 1.4958, 1.4173],
         [1.4071, 0.9219, 1.2044, 1.1518],
         [1.6434, 0.8496, 1.5656, 1.5299],
         [1.1851, 1.2674, 1.4628, 1.3232]],

        [[0.5535, 0.5124, 0.6244, 0.5728],
         [0.9423, 0.7181, 1.3393, 1.2692],
         [1.3950, 1.1789, 1.7150, 1.6110],
         [2.1346, 1.7244, 2.4363, 2.2840]],

        [[0.9444, 1.2560, 1.7472, 1.5768],
         [1.5777, 1.0359, 1.7839, 1.7155],
         [0.6217, 0.9644, 0.8552, 0.7356],
         [1.6186, 1.0539, 1.2581, 1.1998]]])
