In [1]:
import torch 

In [2]:
# Para la realizacion de esta tarea se uso el ejemplo usado en clase. Este ejemplo puede ser encontrado aca: 
# https://github.com/Francososa/ufm-ai-2019/blob/master/tarea_2/tensor-fundamentals.ipynb

In [7]:
# 1. Crear un tensor de list(range(9)) e indicar cual es el size, offset, y stride
one= torch.Tensor(list(range(9)))
print("Stride:", one.stride())
print("Offset:",one.storage_offset())
print("Size:",one.size())


Stride: (1,)
Offset: 0
Size: torch.Size([9])


In [8]:
#1.2 Crear un tensor b = a.view(3, 3). Cual es el valor de b[1, 1]
b = one.view(3,3)
print("El valor es: ",  b[1, 1])

El valor es:  tensor(4.)


In [10]:
#1.3 Crear un tensor b = a.view(3, 3). Cual es el valor de b[1, 1]
c = b[1:, 1:]
print("Stride:", c.stride())
print("Offset:",c.storage_offset())
print("Size:",c.size())


Stride: (3, 1)
Offset: 4
Size: torch.Size([2, 2])


In [16]:
#2.1 Escogan una operacion matematica como cosine o sqrt. Hay una funcion correspondiente en PyTorch?
two = torch.Tensor(list(range(9)))
two = torch.sqrt(two)
print("Si hay, la sintaxis es torch.sqrt(tensor)")
#Existe una version de esa operacion que opera in-place?
torch.sqrt(two)

Si hay, la sintaxis es torch.sqrt(tensor)


tensor([0.0000, 1.0000, 1.1892, 1.3161, 1.4142, 1.4953, 1.5651, 1.6266, 1.6818])

In [119]:
#3.1 Crear un tensor 2D y luego agregar una dimension de tamanio 1 insertada en la dimension 0.
three = torch.Tensor([[list(range(9))],[list(range(9))]])
print("Antes:" ,three.shape)
three1 = three.unsqueeze_(0)
print("Despues:" ,three1.shape)


Antes: torch.Size([2, 1, 9])
Despues: torch.Size([1, 2, 1, 9])


In [120]:
#3.2 Eliminar la dimension extra que agrego en el tensor previo.
three1 =  three1.squeeze_(0)
print("Despues:" ,three1.shape)


Despues: torch.Size([2, 1, 9])


In [129]:
#3.3 Crear un tensor aleatorio de forma $5x3$ en el intervalo $[3,7)$
four = torch.randint(size = [5, 3], low = 3, high = 7)
print(four)

tensor([[6, 5, 5],
        [3, 6, 5],
        [6, 4, 5],
        [4, 6, 4],
        [5, 4, 3]])


In [188]:
#3.4 Crear un tensor con valores de una distribucion normal (mu=0, \sigma=1)
four = torch.distributions.normal.Normal(torch.tensor([0.0]), torch.tensor([1.0]))
four.sample()

tensor([0.9516])

In [131]:
#3.5 Recuperar los indices de todos los elementos no cero en el tensor torch.Tensor([1,1,1,0,1]).
five = torch.Tensor([1,1,1,0,1])
print(torch.nonzero(five))


tensor([[0],
        [1],
        [2],
        [4]])


In [135]:
#3.6 Crear un tensor aleatorio de forma (3,1) y luego apilar cuatro copias horizontalmente.
six  = torch.rand(3, 1)
print(torch.stack([six,six,six,six]))

tensor([[[0.7847],
         [0.0188],
         [0.1415]],

        [[0.7847],
         [0.0188],
         [0.1415]],

        [[0.7847],
         [0.0188],
         [0.1415]],

        [[0.7847],
         [0.0188],
         [0.1415]]])


In [139]:
#3.7 Retornar el producto batch matrix-matrix de dos matrices 3D: (a=torch.randn(3,4,5), b=torch.rand(3,5,4))
a=torch.randn(3,4,5)
b=torch.rand(3,5,4)
print(torch.matmul(a, b, out=None)) 

tensor([[[-0.8102, -0.6124, -0.2646, -0.3386],
         [-0.9136, -0.3051, -0.6601, -0.3010],
         [-2.4041, -1.0384, -0.1704, -1.1726],
         [-0.4967, -0.0741,  0.2470, -0.1503]],

        [[ 2.5766,  2.2033,  1.9809,  3.3701],
         [-1.5125, -0.5243, -1.2782, -1.2661],
         [ 0.9040, -0.8606,  0.5556, -0.3582],
         [-0.7694, -1.0642, -0.6763, -1.3700]],

        [[-2.1030, -0.6410,  0.0073, -0.4085],
         [ 1.3462, -0.6585, -0.2498,  1.3373],
         [ 1.2266,  0.5143, -1.2661, -0.1132],
         [-3.5545, -3.0726, -0.8090, -1.1266]]])


In [144]:
#3.8 Retornar el producto batch matrix-matrix de una matriz 3D y una matriz 2D: (a=torch.rand(3,4,5), b=torch.rand(5,4)).
a=torch.rand(3,4,5)
b=torch.rand(5,4)
print(torch.matmul(a, b, out=None)) 

tensor([[[0.6098, 0.6828, 0.8549, 0.4121],
         [0.5775, 0.7056, 0.7527, 0.3795],
         [1.0705, 1.3503, 1.2397, 0.7532],
         [0.8519, 0.7730, 0.9182, 0.5451]],

        [[0.7817, 0.6745, 1.2381, 0.5016],
         [1.8417, 2.1667, 1.8503, 1.2795],
         [1.2599, 1.1178, 1.3542, 0.8198],
         [0.7794, 0.7118, 0.4394, 0.5315]],

        [[0.5855, 0.6706, 1.0214, 0.3986],
         [1.5632, 1.2416, 1.5335, 1.0446],
         [1.7563, 1.5705, 1.7189, 1.1819],
         [1.1096, 0.7920, 1.1082, 0.7354]]])
