# Tabajo en clase 

In [1]:
import torch

In [2]:
zero_d=torch.tensor(1)

In [7]:
one_d=torch.tensor([1,2,3,4,5])
two_d=torch.tensor([[1,2,3],[4,5,6]])
three_d=torch.ones((3,3,3))

In [8]:
one_d

tensor([1, 2, 3, 4, 5])

In [9]:
two_d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
three_d

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [11]:
points=torch.FloatTensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [12]:
points.storage()[0]

4.0

# Tarea

### 1)  Range of numbers supported by data type

* Uint8: [0, 255]
* Int8:  [-128, 127]
* Int16:  [-32,768, 32,767]
* Int32:  [-2,147,483,648, 2,147,483,647]
* Int64: [-9,223,372,036,854,775,808, 9,223,372,036,854,775,807]
* Float16: [-32,768, 65,536]
* Float32: [-3.4E+38, +3.4E+38]
* Float64: [-1.7E+308, +1.7E+308]

### 2) Int vs. Uint

Por defecto un tipo de dato numérico acepta tanto valores positivos como negativos, por lo cual un int8 por ejemplo que tiene un rango de n valores los cuales debe dividir su rango de valores para asignar la mitad de su rango a valores negativos, el 0 y luego la mitad -1 valores a la escala positiva. Un tipo uint (unsigned int) no posee distinción de signo, permitiendo usar todo el rango disponible para representar números positivos. Este tipo unsigned permite duplicar el valor máximo positivo alcanzado previamente, pero al costo de no poder representar números negativos.

### 3) Default data type used

* Python: int32
* Numpy: int32
* Pytorch: int64