In [1]:
import torch

1. Crear un tensor de list(range(9)) e indicar cual es el size, offset, y strides
 - Crear un tensor b = a.view(3, 3). Cual es el valor de b[1, 1]
 - crear un tensor c = b[1:, 1:]. Cual es el size, offset, strides?

In [2]:
a =torch.tensor(list(range(9)))
print(a,"\n",
      a.size(), "\n",
      a.storage_offset(), "\n",
      a.stride(), "\n")

b = a.view(3,3)
print(b,"\n",
      'valor de b[1,1]: ', b[1,1], "\n")

c = b[1:, 1:]
print(c, "\n",
      c.size(), "\n",
      c.storage_offset(), "\n",
      c.stride())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]) 
 torch.Size([9]) 
 0 
 (1,) 

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) 
 valor de b[1,1]:  tensor(4) 

tensor([[4, 5],
        [7, 8]]) 
 torch.Size([2, 2]) 
 4 
 (3, 1)


2. Escogan una operacion matematica como cosine o sqrt. Hay una funcion correspondiente en PyTorch?

R// Si hay operaciones correspondientes, como `torch.sqrt()`
 - Existe una version de esa operacion que opera in-place?
 Si las hay `torch.sqrt_()` por ejemplo

In [3]:
t1= torch.tensor([[4],
                  [9]], dtype=torch.float)
t2=torch.sqrt(t1)
print(t1, "\n",
t2)

tensor([[4.],
        [9.]]) 
 tensor([[2.],
        [3.]])


1. Crear un tensor 2D y luego agregar una dimension de tamanio 1 insertada en la dimension 0.

In [4]:
a= torch.ones(2,3)
#a.size()
a= a.unsqueeze_(0)
a.size()

torch.Size([1, 2, 3])

2. Eliminar la dimension extra que agrego en el tensor previo.

In [5]:
a= a.resize_(2,3)
a.size()

torch.Size([2, 3])

3. Crear un tensor aleatorio de forma $5x3$ en el intervalo $[3,7)$

In [6]:
b=torch.randint(low=3, high=7, size=(5,3))
b

tensor([[5, 5, 3],
        [5, 3, 3],
        [4, 6, 5],
        [3, 4, 6],
        [3, 5, 5]])

4. Crear un tensor con valores de una distribucion normal ($\mu=0, \sigma=1$)

In [7]:
d= torch.normal(mean= 0, std=torch.ones(2,3))
d

tensor([[ 0.4723, -0.9600,  2.0407],
        [-1.6245, -0.1895, -0.8734]])

5. Recuperar los indices de todos los elementos no cero en el tensor `torch.Tensor([1,1,1,0,1])`.

In [8]:
e=torch.tensor([1,1,1,0,1])
e.nonzero()

tensor([[0],
        [1],
        [2],
        [4]])

6. Crear un tensor aleatorio de forma `(3,1)` y luego apilar cuatro copias horizontalmente.

In [9]:
f = torch.rand(3, 1)
f = torch.stack([f, f, f, f])
f

tensor([[[0.6887],
         [0.1290],
         [0.1486]],

        [[0.6887],
         [0.1290],
         [0.1486]],

        [[0.6887],
         [0.1290],
         [0.1486]],

        [[0.6887],
         [0.1290],
         [0.1486]]])

7. Retornar el producto batch matrix-matrix de dos matrices 3D: (`a=torch.randn(3,4,5)`, `b=torch.rand(3,5,4)`)

In [10]:
a=torch.rand(3,4,5)
b=torch.rand(3,5,4)
g= torch.bmm(a,b)
g

tensor([[[1.8416, 2.2069, 2.0041, 0.8981],
         [1.0662, 1.4985, 1.3724, 0.9402],
         [1.1003, 1.3296, 1.6113, 0.7753],
         [0.7391, 1.3698, 1.2983, 0.9349]],

        [[1.5380, 1.6493, 1.0868, 1.5124],
         [1.2288, 1.6396, 0.9091, 1.1154],
         [1.4141, 1.1133, 1.0657, 0.9313],
         [1.2130, 1.8728, 0.9698, 1.6129]],

        [[0.8051, 1.4262, 2.2538, 1.0120],
         [1.3039, 1.8601, 2.6732, 1.1664],
         [0.8867, 1.2363, 1.7761, 0.7631],
         [0.7220, 1.3290, 1.7226, 0.8052]]])

8. Retornar el producto batch matrix-matrix de una matriz 3D y una matriz 2D: (`a=torch.rand(3,4,5)`, `b=torch.rand(5,4)`).

In [11]:
a=torch.rand(3,4,5)
b=torch.rand(5,4)
h= torch.bmm(a, b.expand(3,5,4))
h

tensor([[[1.6725, 1.4047, 1.3834, 1.9986],
         [1.1697, 1.0838, 1.0485, 1.0516],
         [1.5325, 1.4174, 1.5184, 1.7292],
         [0.6990, 0.6049, 0.9849, 1.2010]],

        [[1.2292, 1.1698, 1.5858, 1.8061],
         [1.4920, 1.2780, 1.3298, 1.7678],
         [1.3729, 0.8908, 0.6203, 1.3327],
         [1.3327, 0.9294, 0.7175, 1.2093]],

        [[0.8257, 0.7242, 0.9955, 1.1039],
         [1.7232, 1.4118, 1.3107, 1.8797],
         [1.2127, 1.0694, 0.9353, 1.2164],
         [1.0588, 0.8371, 0.8498, 1.1486]]])